module Teleport
  class Install
    include Constants    
    include Util
    include Mirror    
    
    attr_reader :config, :host
    
    def initialize(config)
      @config = config
      run_verbose!
      _run
    end

    #
    # public API
    #

    def user
      config.user
    end

    def role
      @role && @role.name
    end

    def install_packages(*list)
      list.flatten.each do |i|
        package_if_necessary(i)
      end
    end

    #
    # private API
    #

    def _run
      _root!
      _config
      _gems
      _hostname
      _create_user
      _apt
      _packages
      _files
    end

    def _root!
      # become root if necessary
      return if whoami == "root"
      
      if fails?("sudo -n echo gub")
        fatal("Please setup sudo for #{user}.")
      end
      banner "Becoming root..."
      $stdout.flush
      exec("sudo ruby -I gem -r teleport -e \"Teleport::Main.new(:install)\"") 
    end

    def _config
      # read DIR/config to get CONFIG_HOST (and set @host)
      config_file = { }
      File.readlines("config").each do |i|
        if i =~ /CONFIG_([^=]+)='([^']*)'/
          config_file[$1.downcase.to_sym] = $2
        end
      end
      @host = config_file[:host]

      # do we have a server object?
      @server = config.server(@host)
      if !@server && !config.servers.empty?
        fatal "Hm. I couldn't find server #{@host.inspect} in teleport.rb."
      end

      @role = nil
      if @server && (role_name = @server.options[:role])
        @role = config.role(role_name)
        if !@role
          fatal "Hm. I couldn't find role #{role_name.inspect} in teleport.rb."
        end
      end
    end

    def _gems
      banner "Gems..."
      
      # update rubygems if necessary
      gem_version = `gem --version`.strip.split(".").map(&:to_i)
      if (gem_version <=> RUBYGEMS.split(".").map(&:to_i)) == -1
        banner "Upgrading rubygems..."
        run "gem update --system"
      end
      
      # uninstall all gems except for bundler
      gems = `gem list`.split("\n").map { |i| i.split.first }
      gems.delete("bundler")
      if !gems.empty?
        banner "Uninstalling #{gems.length} system gems..."
        gems.each do |i|
          run "gem uninstall -aIx #{i}"
        end
      end
      
      # install bundler
      gem_if_necessary("bundler")
    end

    def _hostname
      banner "Hostname..."      
      old_hostname = `hostname`.strip
      return if old_hostname == @host
      
      banner "Setting hostname to #{@host} (it was #{old_hostname})..."
      File.open("/etc/hostname", "w") do |f|
        f.write @host
      end
      run "hostname -F /etc/hostname"

      banner "Fixing up /etc/hosts..."
      _rewrite("/etc/hosts") do |fout|
        File.open("/etc/hosts") do |fin|
          while line = fin.gets
            line = line.gsub(/\b#{Regexp.escape(old_hostname)}\b/, @host)
            fout.write line
          end
        end
      end
    end

    def _create_user
      banner "#{user} account..."
      # create the account
      if !File.directory?("/home/#{user}")
        run "useradd --create-home --shell /bin/bash --groups adm #{user}"
      end
      if fails?("grep '^#{user}' /etc/sudoers.d/teleport")
        banner "Setting up sudoers..."
        File.open("/etc/sudoers.d/teleport", "w") do |f|
          f.puts "# Generated by teleport"
          f.puts "#{user} ALL=(ALL) NOPASSWD: ALL"
        end
        chmod("/etc/sudoers.d/teleport", 0440)
      end

      # ssh key, if present
      authorized_keys = "/home/#{user}/.ssh/authorized_keys"
      if !File.exists?(authorized_keys)
        if File.exists?(PUBKEY)
          mkdir_if_necessary(File.dirname(authorized_keys), user, 0700)
          cp(PUBKEY, authorized_keys, user, 0600)
        end
      end
    end

    def _apt
      return if @config.apt.empty?
      banner "Apt..."

      dirty = false
      
      # keys
      keys = @config.apt.map { |i| i.options[:key] }.compact
      keys.each do |i|
        if fails?("apt-key list | grep #{i}")
          run "apt-key adv --keyserver keyserver.ubuntu.com --recv #{i}"
          dirty = true
        end
      end

      # teleport.list
      apt = @config.apt.sort_by { |i| i.line }
      rewrite = _rewrite("/etc/apt/sources.list.d/teleport.list") do |f|
        f.puts "# Generated by teleport"
        apt.each do |i|
          f.puts i.line
        end
      end

      if dirty || rewrite
        run "apt-get update"
      end
    end

    def _packages
      banner "Packages..."
      packages = config.packages
      packages += @role.packages if @role
      packages += @server.packages if @server
      install_packages(packages)
    end

    def _files
      banner "Files..."
      files = ["files"]
      files << "files_#{role}" if role
      files.each do |i|
        install_dir(i) if File.exists?("#{DATA}/#{i}")
      end
    end

    #
    # helpers
    #

    def _rewrite(path, &block)
      tmp = "#{path}.tmp"
      begin
        File.open(tmp, "w") { |f| yield(f) }
        if !File.exists?(path) || different?(path, tmp)
          copy_perms(path, tmp) if File.exists?(path)
          mv(tmp, path)
          return true
        end
      ensure
        File.unlink(tmp) if File.exists?(tmp)
      end
      false
    end
  end
end
