module Teleport
  class Install
    include Constants    
    include Util
    include Mirror    
    
    def initialize(config)
      @config = config
    end

    def run
      run_verbose!
      read_config

      # setup @config
      Config::DSL.const_set("HOST", @host)
      Config::DSL.const_set("USER", user)
      Config::DSL.const_set("ROLE", @role && @role.name)
      
      with_callback(:install) do
        gems
        hostname
        with_callback(:user) do
          create_user
        end
        apt
        with_callback(:packages) do
          packages
        end
        with_callback(:files) do
          files
        end
      end
    end

    def read_config
      # read DIR/config to get CONFIG_HOST (and set @host)
      config_file = { }
      File.readlines("config").each do |i|
        if i =~ /CONFIG_([^=]+)='([^']*)'/
          config_file[$1.downcase.to_sym] = $2
        end
      end
      @host = config_file[:host]

      # do we have a server object?
      @server = @config.server(@host)
      if !@server && !@config.servers.empty?
        fatal "Hm. I couldn't find server #{@host.inspect} in teleport.rb."
      end

      @role = nil
      if @server && (role_name = @server.options[:role])
        @role = @config.role(role_name)
        if !@role
          fatal "Hm. I couldn't find role #{role_name.inspect} in teleport.rb."
        end
      end
    end

    def gems
      banner "Gems..."
      
      # update rubygems if necessary
      gem_version = `gem --version`.strip.split(".").map(&:to_i)
      if (gem_version <=> RUBYGEMS.split(".").map(&:to_i)) == -1
        banner "Upgrading rubygems..."
        run "gem update --system"
      end
      
      # uninstall all gems except for bundler
      gems = `gem list`.split("\n").map { |i| i.split.first }
      gems.delete("bundler")
      if !gems.empty?
        banner "Uninstalling #{gems.length} system gems..."
        gems.each do |i|
          run "gem uninstall -aIx #{i}"
        end
      end
      
      # install bundler
      gem_if_necessary("bundler")
    end

    def hostname
      banner "Hostname..."      
      old_hostname = `hostname`.strip
      return if old_hostname == @host
      
      banner "Setting hostname to #{@host} (it was #{old_hostname})..."
      File.open("/etc/hostname", "w") do |f|
        f.write @host
      end
      run "hostname -F /etc/hostname"

      banner "Fixing up /etc/hosts..."
      rewrite("/etc/hosts") do |fout|
        File.open("/etc/hosts") do |fin|
          while line = fin.gets
            line = line.gsub(/\b#{Regexp.escape(old_hostname)}\b/, @host)
            fout.write line
          end
        end
      end
    end

    def create_user
      banner "#{user} account..."
      # create the account
      if !File.directory?("/home/#{user}")
        run "useradd --create-home --shell /bin/bash --groups adm #{user}"
      end
      if fails?("grep '^#{user}' /etc/sudoers.d/teleport")
        banner "Setting up sudoers..."
        File.open("/etc/sudoers.d/teleport", "w") do |f|
          f.puts "# Generated by teleport"
          f.puts "#{user} ALL=(ALL) NOPASSWD: ALL"
        end
        chmod("/etc/sudoers.d/teleport", 0440)
      end

      # ssh key, if present
      authorized_keys = "/home/#{user}/.ssh/authorized_keys"
      if !File.exists?(authorized_keys)
        if File.exists?(PUBKEY)
          mkdir_if_necessary(File.dirname(authorized_keys), user, 0700)
          cp(PUBKEY, authorized_keys, user, 0600)
        end
      end
    end

    def apt
      return if @config.apt.empty?
      banner "Apt..."

      dirty = false
      
      # keys
      keys = @config.apt.map { |i| i.options[:key] }.compact
      keys.each do |i|
        if fails?("apt-key list | grep #{i}")
          run "apt-key adv --keyserver keyserver.ubuntu.com --recv #{i}"
          dirty = true
        end
      end

      # teleport.list
      apt = @config.apt.sort_by { |i| i.line }
      rewrite = rewrite("/etc/apt/sources.list.d/teleport.list") do |f|
        f.puts "# Generated by teleport"
        apt.each do |i|
          f.puts i.line
        end
      end

      if dirty || rewrite
        run "apt-get update"
      end
    end

    def packages
      banner "Packages..."
      list = @config.packages
      list += @role.packages if @role
      list += @server.packages if @server
      list.sort.each { |i| package_if_necessary(i) }
    end

    def files
      banner "Files..."
      files = ["files"]
      files << "files_#{@role.name}" if @role
      files.each do |i|
        install_dir(i) if File.exists?("#{DATA}/#{i}")
      end
    end

    #
    # helpers
    #

    def user
      @config.user
    end

    def with_callback(op, &block)
      if before = @config.callbacks["before_#{op}".to_sym]
        before.call
      end
      yield
      if after = @config.callbacks["after_#{op}".to_sym]
        after.call
      end
    end

    def rewrite(path, &block)
      tmp = "#{path}.tmp"
      begin
        File.open(tmp, "w") { |f| yield(f) }
        if !File.exists?(path) || different?(path, tmp)
          copy_perms(path, tmp) if File.exists?(path)
          mv(tmp, path)
          return true
        end
      ensure
        File.unlink(tmp) if File.exists?(tmp)
      end
      false
    end
  end
end
